version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB: nombre_de_la_base_de_datos
      - POSTGRES_USER: usuario_de_la_base_de_datos
      - POSTGRES_PASSWORD: contraseña_de_la_base_de_datos
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=nombre_de_la_base_de_datos
      - DATABASE_USER=usuario_de_la_base_de_datos
      - DATABASE_PASSWORD=contraseña_de_la_base_de_datos
    depends_on:
      - db
volumes:
  postgres_data: